import type { DiaryPost, LiveEvent, News, Song } from "./types";

/**
 * シードコンテンツ。
 * - Supabase が未設定/接続エラーの場合のフォールバック表示に使う
 * - `supabase/seed.sql` と内容を揃えてある
 * 旧ホームページ・eggs の公開情報を元にした初期データ + サンプル記事。
 * 管理画面からいつでも書き換え可能。
 */

export const seedNews: News[] = [
  {
    id: "seed-news-1",
    title: "オフィシャルサイトをリニューアルしました",
    body: "天邪鬼の新しい根城が完成。ライブ情報・楽曲紹介・メンバー日記をここから発信していきます。ブックマークよろしくどうぞ。",
    category: "info",
    published_at: "2026-08-16T12:00:00+09:00",
    is_published: true,
  },
  {
    id: "seed-news-2",
    title: "6曲入りCD「Late Show」発売中",
    body: "2019年5月リリースの自主制作CD「Late Show」、ライブ会場にて絶賛発売中です。手売りこそロックの基本。",
    category: "release",
    published_at: "2019-05-01T12:00:00+09:00",
    is_published: true,
  },
  {
    id: "seed-news-3",
    title: "HOTLINE2018 神奈川エリアファイナル ベストギター賞受賞",
    body: "2年連続でベストギター賞をいただきました。しぶといギターはまだまだ枯れません。",
    category: "media",
    published_at: "2018-10-20T12:00:00+09:00",
    is_published: true,
  },
  {
    id: "seed-news-4",
    title: "HOTLINE2017 優秀賞・ベストギター賞・審査員特別賞受賞",
    body: "HOTLINE2017 神奈川エリアファイナルにて三冠。応援ありがとうございました。",
    category: "media",
    published_at: "2017-10-15T12:00:00+09:00",
    is_published: true,
  },
];

export const seedSongs: Song[] = [
  {
    id: "seed-song-1",
    slug: "suteta-hazu-no-machi",
    title: "捨てたはずの街",
    reading: "すてたはずのまち",
    description:
      "天邪鬼の代名詞。一度は背を向けた街への未練と意地を、60年代由来の骨太なギターリフに乗せて叩きつける。HOTLINEのエリアファイナルでも披露してきた、ライブ終盤の定番曲。\n\n最後のコーラスで景色がひっくり返る瞬間を、ぜひフロアで浴びてほしい。",
    catch_copy: "一度捨てた街に、もう一度殴り込む。",
    release: "Late Show (2019)",
    track_no: 1,
    duration: null,
    tags: ["GUITAR ROCK", "ANTHEM", "LIVE定番"],
    eggs_url: "https://eggs.mu/artist/amanojoker",
    youtube_url: null,
    accent_color: "#e63a21",
    sort_order: 1,
    is_published: true,
  },
  {
    id: "seed-song-2",
    slug: "pose",
    title: "POSE",
    reading: "ポーズ",
    description:
      "斜に構えた奴らへの応援歌。つんのめるビートと噛みつくようなボーカルで、「格好つけることの何が悪い」と開き直る一曲。\n\nHOTLINE'18 神奈川エリアファイナルでは「捨てたはずの街」とのメドレーで披露された。",
    catch_copy: "格好つけることの、何が悪い。",
    release: "Late Show (2019)",
    track_no: 2,
    duration: null,
    tags: ["ROCK'N'ROLL", "UPPER"],
    eggs_url: "https://eggs.mu/artist/amanojoker",
    youtube_url: null,
    accent_color: "#ff5638",
    sort_order: 2,
    is_published: true,
  },
  {
    id: "seed-song-3",
    slug: "iro-no-sabaku",
    title: "色の砂漠",
    reading: "いろのさばく",
    description:
      "タンゴの足取りで進む異色のナンバー。乾いた街の風景に、ラテンの熱と昭和歌謡の湿り気を同時に流し込む。天邪鬼の「雑食」が最もよく出た一曲。\n\n鳴らすたびに景色の色が変わる、砂漠のような曲。",
    catch_copy: "タンゴの足取りで、砂漠に紅を差す。",
    release: "Late Show (2019)",
    track_no: 3,
    duration: null,
    tags: ["TANGO", "MOODY"],
    eggs_url: "https://eggs.mu/artist/amanojoker",
    youtube_url: null,
    accent_color: "#c9a227",
    sort_order: 3,
    is_published: true,
  },
  {
    id: "seed-song-4",
    slug: "asayake",
    title: "朝焼け",
    reading: "あさやけ",
    description:
      "夜通し鳴らしたあとの、静かな祈りのようなバラード。フォークの肌触りとゴスペルめいたコーラスで、夜の終わりをそっと看取る。\n\nHOTLINE'17 のステージでは「捨てたはずの街」からこの曲へ雪崩れ込む構成で披露された。",
    catch_copy: "夜通し騒いだあとの、静かな祈り。",
    release: "Late Show (2019)",
    track_no: 4,
    duration: null,
    tags: ["FOLK", "BALLAD"],
    eggs_url: "https://eggs.mu/artist/amanojoker",
    youtube_url: null,
    accent_color: "#d97b4a",
    sort_order: 4,
    is_published: true,
  },
  {
    id: "seed-song-5",
    slug: "uso-wo-tsuku-shojikimono",
    title: "うそをつく正直者",
    reading: "うそをつくしょうじきもの",
    description:
      "2015年発表の1stデモ表題曲にして、バンド名「天邪鬼」の精神をそのまま音にした原点。本心を裏返してしか喋れない男の歌。\n\n荒削りだが、今も昔もセットリストの芯にいる。",
    catch_copy: "本心は、いつも裏返しで。",
    release: "1st demo「うそをつく正直者」(2015)",
    track_no: 1,
    duration: null,
    tags: ["DEMO", "ORIGIN"],
    eggs_url: "https://eggs.mu/artist/amanojoker",
    youtube_url: null,
    accent_color: "#8c8c8c",
    sort_order: 5,
    is_published: true,
  },
];

export const seedLives: LiveEvent[] = [
  {
    id: "seed-live-1",
    title: "LIVE at 新宿ゴールデンエッグ",
    date: "2023-02-25",
    open_time: "18:00",
    start_time: "18:30",
    venue: "新宿ゴールデンエッグ",
    area: "東京",
    ticket_price: null,
    note: null,
    link_url: null,
    is_published: true,
  },
  {
    id: "seed-live-2",
    title: "LIVE at 代々木barbara",
    date: "2023-01-08",
    open_time: null,
    start_time: null,
    venue: "代々木barbara",
    area: "東京",
    ticket_price: null,
    note: null,
    link_url: null,
    is_published: true,
  },
  {
    id: "seed-live-3",
    title: "LIVE at 代々木barbara",
    date: "2022-12-16",
    open_time: null,
    start_time: null,
    venue: "代々木barbara",
    area: "東京",
    ticket_price: null,
    note: null,
    link_url: null,
    is_published: true,
  },
  {
    id: "seed-live-4",
    title: "LIVE at 代々木barbara",
    date: "2022-10-08",
    open_time: null,
    start_time: null,
    venue: "代々木barbara",
    area: "東京",
    ticket_price: null,
    note: null,
    link_url: null,
    is_published: true,
  },
  {
    id: "seed-live-5",
    title: "LIVE at 下北沢ろくでもない夜",
    date: "2022-08-14",
    open_time: null,
    start_time: null,
    venue: "下北沢ろくでもない夜",
    area: "東京",
    ticket_price: null,
    note: null,
    link_url: null,
    is_published: true,
  },
  {
    id: "seed-live-6",
    title: "LIVE at 下北沢ろくでもない夜",
    date: "2022-06-10",
    open_time: null,
    start_time: null,
    venue: "下北沢ろくでもない夜",
    area: "東京",
    ticket_price: null,
    note: null,
    link_url: null,
    is_published: true,
  },
  {
    id: "seed-live-7",
    title: "LIVE at 根岸 New Inver House",
    date: "2022-05-03",
    open_time: null,
    start_time: null,
    venue: "根岸 New Inver House",
    area: "神奈川",
    ticket_price: null,
    note: null,
    link_url: null,
    is_published: true,
  },
  {
    id: "seed-live-8",
    title: "LIVE at 関内 b.b street",
    date: "2022-03-12",
    open_time: null,
    start_time: null,
    venue: "関内 b.b street",
    area: "神奈川",
    ticket_price: null,
    note: null,
    link_url: null,
    is_published: true,
  },
  {
    id: "seed-live-9",
    title: "LIVE at 下北沢LIVEHOLIC",
    date: "2022-02-23",
    open_time: null,
    start_time: null,
    venue: "下北沢LIVEHOLIC",
    area: "東京",
    ticket_price: null,
    note: null,
    link_url: null,
    is_published: true,
  },
  {
    id: "seed-live-10",
    title: "LIVE at 下北沢ろくでもない夜",
    date: "2021-12-12",
    open_time: null,
    start_time: null,
    venue: "下北沢ろくでもない夜",
    area: "東京",
    ticket_price: null,
    note: null,
    link_url: null,
    is_published: true,
  },
  {
    id: "seed-live-11",
    title: "LIVE at 西横浜エルプエンテ",
    date: "2021-10-31",
    open_time: null,
    start_time: null,
    venue: "西横浜エルプエンテ",
    area: "神奈川",
    ticket_price: null,
    note: null,
    link_url: null,
    is_published: true,
  },
  {
    id: "seed-live-12",
    title: "LIVE at 下北沢 Daisy Bar",
    date: "2021-01-15",
    open_time: null,
    start_time: null,
    venue: "下北沢 Daisy Bar",
    area: "東京",
    ticket_price: null,
    note: null,
    link_url: null,
    is_published: true,
  },
];

export const seedDiary: DiaryPost[] = [
  {
    id: "seed-diary-1",
    slug: "site-renewal",
    title: "根城、新築しました",
    body: "というわけで、オフィシャルサイトをリニューアルした。\n\n前のサイトも長いこと世話になったが、そろそろ日記も曲の話も、もっと好き勝手に書ける場所が欲しくなった。ここがその場所である。\n\n## これから書くこと\n\n- ライブの告知と、終わったあとの反省文\n- 曲がどうやってできたかという与太話\n- メンバーの近況(主に飯の話になる予感)\n\n更新は気まぐれ、内容は本音の裏返し。天邪鬼の日記とはそういうものだ。\n\nよろしくどうぞ。",
    author: "ウノ太一",
    mood: "上機嫌",
    cover_kanji: "新",
    published_at: "2026-08-16T21:00:00+09:00",
    is_published: true,
  },
  {
    id: "seed-diary-2",
    slug: "late-show-no-hanashi",
    title: "「Late Show」という名前について",
    body: "たまに訊かれるので、CDのタイトルの話を書いておく。\n\n「Late Show」——深夜興行。誰もが寝静まった時間に、それでも幕を開ける見世物のこと。\n\n俺たちのやっている音楽は、流行の真ん中からは外れているのかもしれない。60年代や70年代のロックを土台に、タンゴだのフォークだの、古い道具ばかり並べている。\n\n> でも深夜の映画館には、深夜の映画館にしか来ない客がいる。\n\nそういう客に向けて鳴らす6曲だから、「Late Show」。手売りで買ってくれたあなたは、間違いなくその客である。\n\n次の興行でお会いしましょう。",
    author: "ウノ太一",
    mood: "夜型",
    cover_kanji: "夜",
    published_at: "2026-08-10T02:00:00+09:00",
    is_published: true,
  },
  {
    id: "seed-diary-3",
    slug: "tango-to-rock",
    title: "タンゴとロックは親戚である",
    body: "「色の砂漠」を作ったときから考えていることを書く。\n\nタンゴとロックンロールは、遠い親戚だと思っている。どちらも港町の音楽で、どちらも行儀が悪くて、どちらも踊るための音楽だったのに、いつの間にか「聴くもの」になってしまった。\n\n## だから俺たちは混ぜる\n\nベースのバーボンが刻む2拍子の上で、ギターが泣く。ドラムのアトランティスが笑いながら、一番いい太鼓を叩く。\n\nジャンルの垣根なんてものは、またいで初めて意味がある。\n\n温故知新、雑食上等。それが→NEW OLD←である。",
    author: "ウノ太一",
    mood: "考察",
    cover_kanji: "混",
    published_at: "2026-07-28T23:30:00+09:00",
    is_published: true,
  },
  {
    id: "seed-diary-4",
    slug: "takadanobaba-2013",
    title: "高田馬場、2013年の秋",
    body: "結成の話を、記録として残しておく。\n\n2013年10月、高田馬場。「最近のロックは行儀が良すぎる」——そんな不満から、このバンドは始まった。行儀の悪いロックがやりたいなら、自分たちでやるしかない。\n\nそこから十年以上。ドラマーが加わって今の三人になり、賞をいくつかもらい、CDを作り、いまもライブハウスのフロアに立っている。\n\n行儀はいまだに悪いままである。安心してほしい。\n\n※この日記はサイト移転にあわせて書き直した再録である。",
    author: "ウノ太一",
    mood: "回想",
    cover_kanji: "始",
    published_at: "2026-07-15T22:00:00+09:00",
    is_published: true,
  },
];
